# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v2.2.4
      with:
          version: 6.0.2
    - run: pnpm i
    - run: pnpm build

    - uses: actions/checkout@v3
    - name: copy
      run: |
        rm -rf /var/www/wip
        cp -r /root/actions-runner/_work/xavivila.dev/xavivila.dev/dist /var/www/wip
